const { faker } = require('@faker-js/faker');
const mysql = require('mysql2');

// create the connection with database
const conn = mysql.createConnection({
    host: '127.0.0.1',
    user: 'root',
    database: 'delta_app',
    password: "12345678"
});


//let q = "SHOW TABLES";
//inserting one record  using placeholder
 let q = "INSERT INTO USER (id, username, email, password) values (?, ?, ?, ?)";
 let userss = ["123","salim", "salim@gmail.com", "12345678"];
try{
 conn.query(q, user, (err, result)=>{
    if(err) throw err;
    console.log(result); //it will print the result of sql query we are sending
 })
}catch(err){
    console.log(err);
}


let users = [["121","Muskan", "Muskan@gmail.com", "hye6836"], ["333","Halima", "halima@gmail.com", "34232"]];

try {
    conn.query(q, [users], (err, result) => {
        if (err) throw err;
        console.log(result);
    });
} catch (err) {
    console.log(err);
}

let q1 = "insert into user (id, username, email, password) values ?";


let createRandomUser = ()=> {
    return {
      Id: faker.string.uuid(),
      username: faker.internet.userName(),
      email: faker.internet.email(),
      password: faker.internet.password(),
    };
  }
console.log(createRandomUser());

//insertin data in the table user in bulk generated by faker

let getRandomUser = () => {
    return [
        faker.string.uuid(),
        faker.internet.userName(),
        faker.internet.email(),
        faker.internet.password(),
    ];
}

let q2 = "insert into user (id, username, email, password) values ?";
let data = [];
for (let i = 1; i <= 100; i++) {
    data.push(getRandomUser());
}

try {
    conn.query(q2, [data], (err, result) => {
        if (err) throw err;
        console.log(result);
    });
} catch (err) {
    console.log(err);
}
/* C:\"Program Files"\MySQL\"MySQL Server 8.0"\bin\mysql.exe -u root -p */  //enter this comand to open the sql in the terminal


conn.end();  //to end the connection automatically